GET http://localhost:8880/hello
#Accept: application/json

> {%
client.test("test-hello", function() {
  client.log("测试/hello接口");
  client.log(response.body);
  client.log(JSON.stringify(response.body)); // 虽然idea没有提示JSON，但是可以用；这段可以用js内置函数
  client.assert(response.status === 200, "返回码不是200");
  client.assert(response.body === "Hello World!", "结果验证失败");
});
%}

###

POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###